### ISSUE TITLE
How to add icon to popup menu

### ISSUE THREAD

**Issue by Torchok19081986** [Abel13/NavigationDrawer#1]
Hallo, im knew im WPF and i saw your video on youtube. First , Video is great. I learned good new feature in wpf. Thanks a lot. 
Only few more questions are left : how to add icon in popup menu on right side ? How to trigger slimenuevent for dynamicly size of usercontrol ?

**Comment by Abel13** [comment]
Hello @Torchok19081986 I'm really sorry about my delay.
Everything is solved?
